timeout: 1
quiet: yes
remember_last_entry: yes

/Arch Linux
    protocol: efi_chainload
    image_path: boot():/EFI/Linux/arch-linux.efi

/Arch Linux (LTS)
    protocol: efi_chainload
    image_path: boot():/EFI/Linux/arch-linux-lts.efi

/Windows
    protocol: efi_chainload
    image_path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
